#!/bin/bash
curl -O https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py
pip3 install virtualenv
cd /home/ec2-user/tradefeeapp
virtualenv environment
source environment/bin/activate
python3 pip3 install -r requirements.txt
python3 pip3 install supervisor
