#!/bin/bash
curl -O https://bootstrap.pypa.io/get-pip.py
sudo python3.2 get-pip.py
cd /home/ec2-user/tradefeeapp
virtualenv environment
source environment/bin/activate
pip install -r requirements.txt
pip install supervisor
